version: "3.2"
services:
  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes: 
      - C:\MSSQL\BACKUP\KEEP:/var/opt/mssql/backups
      - C:\MSSQL\DockerFiles\datafiles:/var/opt/sqlserver
      - C:\MSSQL\DockerFiles\system:/var/opt/mssql